create table public.category_
(
    id     bigint generated by default as identity
        constraint category__pkey
            primary key,
    active boolean,
    name   varchar(255)
);

create table public.customer_
(
    id     bigint generated by default as identity
        constraint customer__pkey
            primary key,
    active boolean
);

create table public.info_
(
    id                 bigint generated by default as identity
        constraint info__pkey
            primary key,
    active             boolean,
    created_by         varchar(255),
    created_date       timestamp,
    deleted            boolean not null,
    last_modified_by   varchar(255),
    last_modified_date timestamp,
    content            text,
    image_url          varchar(255),
    title              varchar(255)
);

create table public.product_
(
    id          bigint generated by default as identity
        constraint product__pkey
            primary key,
    about       varchar(255),
    active      boolean,
    equipment   varchar(255),
    name        varchar(255),
    url_image   varchar(255),
    category_id bigint
        constraint fk9qqf14c64jldb2aok6l6n7tak
            references public.category_
);

create table public.product_agenda_
(
    id          bigint generated by default as identity
        constraint product_agenda__pkey
            primary key,
    day_of_week varchar(255),
    schedule    text,
    product_id  bigint
        constraint fkhrioa5bkxvx41160tw7unsgse
            references public.product_
);

create table public.professional_
(
    id        bigint generated by default as identity
        constraint professional__pkey
            primary key,
    about     text,
    active    boolean,
    count     bigint,
    price     double precision,
    rating    double precision,
    reference varchar(255),
    resume    text
);

create table public.user_
(
    id              bigint generated by default as identity
        constraint user__pkey
            primary key,
    active          boolean,
    avatar_url      varchar(255),
    birthday        date,
    cpf             varchar(255) not null
        constraint uk_pojfj5cxgdgy62oigslhts3ru
            unique,
    email           varchar(255) not null
        constraint uk_ha67cvlhy4nk1prswl5gj1y0y
            unique,
    gender          varchar(255),
    name            varchar(255),
    password        varchar(255),
    phone_number    varchar(255),
    surname         varchar(255),
    username        varchar(255) not null
        constraint uk_wqsqlvajcne4rlyosglqglhk
            unique,
    customer_id     bigint
        constraint fk47c8hivjsg5fde3htyb386pd8
            references public.customer_,
    professional_id bigint
        constraint fk19o4f8gijnw4ly9pt8w3emxh4
            references public.professional_
);

create table public.address_
(
    id           bigint generated by default as identity
        constraint address__pkey
            primary key,
    active       boolean,
    city         varchar(255),
    complement   varchar(255),
    latitude     varchar(255),
    longitude    varchar(255),
    neighborhood varchar(255),
    number       varchar(255),
    state        varchar(255),
    street       varchar(255),
    zipcode      varchar(255),
    user_id      bigint
        constraint fkn0ar4c70k2l5gc8jltj6usi5k
            references public.user_
);

create table public.bankdata_
(
    id              bigint generated by default as identity
        constraint bankdata__pkey
            primary key,
    account         varchar(255),
    account_type    varchar(255),
    agency          varchar(255),
    bank            varchar(255),
    professional_id bigint
        constraint fk1hpr13yge3y69f95wle4uacya
            references public.user_
);

create table public.credit_card_
(
    id                 bigint generated by default as identity
        constraint credit_card__pkey
            primary key,
    brand              varchar(255),
    city               varchar(255),
    country            varchar(255),
    default_card       boolean,
    last_numbers       varchar(255),
    name               varchar(255),
    neighborhood       varchar(255),
    payment_service_id varchar(255),
    state              varchar(255),
    street             varchar(255),
    street_number      varchar(255),
    zipcode            varchar(255),
    user_id            bigint
        constraint fkm1wfqprekpm9l43klpenxetmw
            references public.user_
);

create table public.favorite_
(
    id              bigint generated by default as identity
        constraint favorite__pkey
            primary key,
    professional_id bigint
        constraint fkebig3y4uk4rg8fgy14nj9gljy
            references public.user_,
    user_id         bigint
        constraint fkh8tq0ld5aldsogatnbjjlunj0
            references public.user_
);

create table public.finance_
(
    id                       bigint generated by default as identity
        constraint finance__pkey
            primary key,
    customer_balance         numeric(19, 2),
    customer_payment_profile varchar(255),
    professional_balance     numeric(19, 2),
    user_id                  bigint
        constraint fkpq69y6acq1cs3avxgom6uixlw
            references public.user_
);

create table public.payment_
(
    id            bigint generated by default as identity
        constraint payment__pkey
            primary key,
    card_value    numeric(19, 2),
    payment_type  varchar(255),
    pf_cash_value numeric(19, 2),
    card_id       bigint
        constraint fk2uq083u2i1xmg8n4bj6ar893y
            references public.credit_card_
);

create table public.order_
(
    id                  uuid not null
        constraint order__pkey
            primary key,
    created_at          timestamp,
    date                date,
    end_time            time,
    gender              varchar(255),
    has_sent            boolean,
    is_reviewed         boolean,
    number_of_customers integer,
    start_time          time,
    status              varchar(255),
    total_cost          numeric(19, 2),
    address_id          bigint
        constraint fk8ssagdtkkbb4bkpnws2smcfc7
            references public.address_,
    customer_id         bigint
        constraint fkbduc96b8jsmln03alkmolxhtj
            references public.user_,
    payment_id          bigint
        constraint fkac7fqtg9mhhsx5sj4heirxj
            references public.payment_,
    product_id          bigint
        constraint fki7oxpof4amfg583yos0knliyj
            references public.product_,
    professional_id     bigint
        constraint fklm4v15yjjtcbiau2ry710cukc
            references public.user_
);

create table public.order__available
(
    order_id     uuid   not null
        constraint fkoapwhirxlws47cpkxh6xhfomx
            references public.order_,
    available_id bigint not null
        constraint fk5kkvuir1uxu9p0r8lsr85lnya
            references public.user_
);

create table public.order__response
(
    order_id    uuid   not null
        constraint fk8q3klf1v2t55pqd6hji3j8s2m
            references public.order_,
    response_id bigint not null
        constraint fkj9guqnhp75pbc5hyb8v5ee5s9
            references public.user_
);

create table public.photo_
(
    id        bigint generated by default as identity
        constraint photo__pkey
            primary key,
    image_url varchar(255),
    user_id   bigint
        constraint fk3pccvf98ctql94kk7d0nutwfr
            references public.user_
);

create table public.product__professional
(
    product_id      bigint not null
        constraint fkccxc6yhknf7l89m0vf2c0xlcm
            references public.product_,
    professional_id bigint not null
        constraint fkq9f6c20b0werbnq7vbxortu2k
            references public.user_
);

create table public.professional_agenda_
(
    id          bigint generated by default as identity
        constraint professional_agenda__pkey
            primary key,
    day_of_week varchar(255),
    schedule    text,
    status      varchar(255),
    user_id     bigint
        constraint fk20s1wubtrvphk9dytomkj3dfj
            references public.user_
);

create table public.review_
(
    id              bigint generated by default as identity
        constraint review__pkey
            primary key,
    comment         varchar(255),
    date            date,
    rating          integer,
    customer_id     bigint
        constraint fkmgcnve1yk6aa8l6jh80a36ag4
            references public.user_,
    order_id        uuid
        constraint fkm1ebid7y8hu3u8ok000frvccf
            references public.order_,
    professional_id bigint
        constraint fkotc70sekpod9h1axbn0iv7fb6
            references public.user_
);

create table public.transaction_
(
    id                        bigint generated by default as identity
        constraint transaction__pkey
            primary key,
    active                    boolean,
    created_by                varchar(255),
    created_date              timestamp,
    deleted                   boolean not null,
    last_modified_by          varchar(255),
    last_modified_date        timestamp,
    acquirer_name             varchar(255),
    app_profit                numeric(19, 2),
    app_tax_percentage        numeric(19, 2),
    app_tax_value             numeric(19, 2),
    billing_order_date        date,
    credit_card_value         numeric(19, 2),
    customer_balance_value    numeric(19, 2),
    order_is_done             boolean,
    payment_mdr_tax           numeric(19, 2),
    payment_mdr_value         numeric(19, 2),
    payment_status            varchar(255),
    payment_total_cost        numeric(19, 2),
    payment_transaction_id    varchar(255),
    payment_type              varchar(255),
    processing_cost           numeric(19, 2),
    professional_is_paid      boolean,
    professional_payment_date date,
    professional_value        numeric(19, 2),
    refuse_reason             varchar(255),
    total_paid                numeric(19, 2),
    card_id                   bigint
        constraint fk8o0en6j5jgng27nqo8k4nk1g7
            references public.credit_card_,
    customer_id               bigint
        constraint fkbea8p53w46lx7tmya0i3ysxo7
            references public.user_,
    order_id                  uuid
        constraint fkkfhc59i8q9du58wtaly7csd65
            references public.order_,
    professional_id           bigint
        constraint fkomyhfngt283rb8x2hafpikshe
            references public.user_
);

create table public.user_records_
(
    id                                        bigint generated by default as identity
        constraint user_records__pkey
            primary key,
    create_date                               date,
    customer_expo_push_notification_token     varchar(255),
    device_brand                              varchar(255),
    device_model                              varchar(255),
    device_model_id                           varchar(255),
    device_os_name                            varchar(255),
    device_os_version                         varchar(255),
    last_access_date                          date,
    professional_expo_push_notification_token varchar(255),
    user_id                                   bigint
        constraint fk40u94d13jx9ukkjyq0fj3e6st
            references public.user_
);

create table public.user_role
(
    user_id bigint not null
        constraint fk9j34cgjanbs56h6h7k8xk25wy
            references public.user_,
    role    varchar(255)
);

